# Generated by Django 2.0.3 on 2018-03-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(default='rgb(255,255,165)', max_length=30)),
                ('coordinates', models.TextField()),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
