# Generated by Django 2.0.3 on 2018-03-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_notes', '0004_auto_20180321_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(default='#ffffa5', max_length=30),
        ),
    ]
